### ISSUE TITLE
Default value max_len=None in keras_transformer.decode is dangerous

### ISSUE THREAD

**Issue by Koziev** [CyberZHG/keras-transformer#3]
It is not a bug really. But I think changing it to something like max_len=10000 in https://github.com/CyberZHG/keras-transformer/blob/master/keras_transformer/transformer.py#L395 can be reasonable.

I have spent a half of day debugging the model, trying to find the reason it hangs *sometimes* when predicting with (under)trained model. Well, the problem is <END> sometimes not selected as next token (https://github.com/CyberZHG/keras-transformer/blob/master/keras_transformer/transformer.py#L428), so the condition in https://github.com/CyberZHG/keras-transformer/blob/master/keras_transformer/transformer.py#L430 is always False.

Another option would be raising an error when length of tokens list exceeds some reasonable limit.

**Comment by CyberZHG** [comment]
Thanks. I've changed the default value and made a release. Repeating detection will be considered in the future.
