### ISSUE TITLE
How do you use masking with the transformer?

### ISSUE THREAD

**Issue by rajicon** [CyberZHG/keras-transformer#31]
I'm having trouble figuring out how to use masking with the transformer.  I have mask_zero set to true with the embeddings, but I'm not sure if the masking is used in the transformer calculation.  Do I need to do anything special to make sure it is taken into account?

For example,  if I was putting a sentence through the encoder: (2 3 2 1 0 0 0), and I want the transformer to ignore the zeros, what should I do?  (The 0 embedding is a zero vector, if that matters).

**Comment by BruceJust** [comment]
i saw mask_zero was default setting, you can find it in the file transformer.py,
mask_zero=True , also there exist mask calculate in attention layer
