### ISSUE TITLE
Tensorflow dependency remove

### ISSUE THREAD

**Issue by flydsc** [CyberZHG/keras-transformer#6]
Hi, thank you for these handy tool box, really helpful.

And one issue I met is I had to download tensorflow every time when I tried to install from pypi or this git repository.

I think the reason is I installed tensorflow GPU version, the package's name is tensorflow-gpu in pypi, however in the dependency file, we always get name of tensorflow, like in requirement file.

May I suggest to remove some common basic packages like tensorflow and keras since users open had these tools installed already.

**Comment by CyberZHG** [comment]
CyberZHG/torch-transformer#1
