### ISSUE TITLE
Use it as a layer

### ISSUE THREAD

**Issue by guyko81** [CyberZHG/keras-transformer#9]
Can you share an example where it is used as an internal layer in a model besides other keras layers? Many thanks!

**Comment by mokundong** [comment]
+1

**Comment by CyberZHG** [comment]
Encoders and decoders can be constructed individually. Following is an example in [keras-bert](https://github.com/CyberZHG/keras-bert):

https://github.com/CyberZHG/keras-bert/blob/9db7ad2a7f3c332ca5fd0247816603a39c917c58/keras_bert/bert.py#L93-L102

You can find more in [dependents](https://github.com/CyberZHG/keras-transformer/network/dependents).
